name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t auth-service:latest .

      - name: Push Docker image
        run: |
          docker tag auth-service:latest yourdockerhubusername/auth-service:latest
          docker push yourdockerhubusername/auth-service:latest

